name: 'Diploi Builder Action'
description: 'An action that builds components from a Diploi stack'
branding:
  icon: 'package'
  color: 'purple'

inputs:
  identifier:
    description: 'The identifier for the component'
    required: true
  folder:
    description: 'The folder for the component'
    required: true
  dockerfile:
    description: 'Optional name for the Dockerfile to use'
  prefix:
    description: 'Optional prefix to add to the built image tags'
  project:
    description: 'Project name for the Diploi Docker registry'
    required: true
  registry:
    description: 'Hostname for the Diploi Docker registry'
    required: true
  username:
    description: 'User for the Diploi Docker registry'
    required: true
  password:
    description: 'Password for the Diploi Docker registry'
    required: true

runs:
  using: composite
  steps:
    - name: 'Set up QEMU'
      uses: docker/setup-qemu-action@v3

    - name: 'Set up Docker Buildx'
      uses: docker/setup-buildx-action@v3

    - name: 'Docker Meta'
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.registry }}/${{ env.project }}/${{ inputs.identifier }}
        tags: ${{ inputs.prefix && 'type=ref,event=branch\ntype=ref,event=branch,prefix=${{ inputs.prefix }}-' || 'type=ref,event=branch' }}

    - name: 'Log in to the Diploi Container Registry'
      uses: docker/login-action@v2
      with:
        registry: ${{ env.registry }}
        username: ${{ env.username }}
        password: ${{ env.password }}

    - name: 'Build And Push'
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.folder }}
        file: ${{ inputs.folder }}/${{ inputs.dockerfile || 'Dockerfile' }}
        pull: true
        push: ${{ github.event_name != 'pull_request' }}
        platforms: linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
